### ISSUE TITLE
Feedback para erros de formulario

### ISSUE THREAD

**Issue by neuberoliveira** [grupo2projeto/Doe-Acao-Front#20]
Uma coisa muito importante sobre formularios e dar feedback sobre o que aconteceu, onde esta o erro, qual o problema etc...

![Screen Shot 2023-11-27 at 11 04 17](https://github.com/grupo2projeto/Doe-Acao-Front/assets/3378304/e2b5ccef-eb46-442f-83c5-a5ee37bec88f)

apesar de ter feito de proposito, se fosse algo mais sutil nao tem como saber o que de fato esta errado, as senhas nao batem? data de nascimento? cnpj?

botar o focus() no campo, dar um destaque, borda vermelha, texto, pisca, rodopia, sei la, quem estiver usando precisa saber como preencher o campo

**Comment by neuberoliveira** [comment]
Tipo agora, botei todos os dados "certos" inclusive a senha que ta limpando em cada submit, e nao faco idea do que ta errado agora rsrsr

![Screen Shot 2023-11-27 at 11 41 59](https://github.com/grupo2projeto/Doe-Acao-Front/assets/3378304/01c655f6-9e1b-4c99-af44-ea36906a81ce)

**Comment by neuberoliveira** [comment]
descobri que precisa ter no minimo 8 caracteres de senha ;)

**Comment by nathanccoelho** [comment]
Simmmm, vamos atualizar!

**Comment by nathanccoelho** [comment]
![Validações](https://github.com/grupo2projeto/Doe-Acao-Front/assets/142533697/85910437-1717-4005-8ed1-67706dd58d9e)

Atualizamos as validações nos campos de cadastro e implementamos o mostrar senha no cadastro e Login.
